/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeryzhang_common_jnttest2_StringUtil */

#ifndef _Included_com_jeryzhang_common_jnttest2_StringUtil
#define _Included_com_jeryzhang_common_jnttest2_StringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeryzhang_common_jnttest2_StringUtil
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jeryzhang_common_jnttest2_StringUtil_getStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
